Support Wayland in hasher

diff --git a/hasher b/hasher
--- a/hasher
+++ b/hasher
@@ -1,38 +1,48 @@
 #!/bin/bash
 
 ui_check () {
-    if [ "$(which sha1sum 2> /dev/null)" = "" ] ; then
+    if [[ "$(which sha1sum 2> /dev/null)" = "" ]] ; then
         echo '"sha1sum" is required.'
-        [ "$(uname -s)" = "Darwin" ] && echo 'Use "brew install coreutils" to install it.'
+        [[ "$(uname -s)" = "Darwin" ]] && echo 'Use "brew install coreutils" to install it.'
         exit 1
     fi
 
-    if [ "$(uname -s)" = "Darwin" ] ; then
+    if [[ "$(uname -s)" = "Darwin" ]] ; then
         IS_DARWIN=1
         return
     fi
 
-    [ "$(which zenity 2> /dev/null)" != "" ] && HAS_ZENITY=1
-    [ "$(which kdialog 2> /dev/null)" != "" ] && HAS_KDIALOG=1
+    [[ "$(which zenity 2> /dev/null)" != "" ]] && HAS_ZENITY=1
+    [[ "$(which kdialog 2> /dev/null)" != "" ]] && HAS_KDIALOG=1
 
-    if [ "${HAS_ZENITY}${HAS_KDIALOG}" = "" ] ; then
+    if [[ "${HAS_ZENITY}${HAS_KDIALOG}" = "" ]] ; then
         echo '"zenity" or "kdialog" is required or user interraction.'
         exit 1
     fi
 
-    [ "$(which xsel 2> /dev/null)" != "" ] && HAS_XSEL=1
-    [ "$(which xclip 2> /dev/null)" != "" ] && HAS_XCLIP=1
+    if [[ "$XDG_SESSION_TYPE" = "wayland" ]] ; then
+        IS_WAYLAND=1
+        [[ "$(which wl-copy 2> /dev/null)" != "" ]] && HAS_WLCOPY=1
 
-    if [ "${HAS_XSEL}${HAS_XCLIP}" = "" ] ; then
-        echo '"xsel" (preferred) or "xclip" is required to be able to copy to the clipboard.'
-        exit 1
+        if [[ "$HAS_WLCOPY" = "" ]] ; then
+            echo '"wl-copy" is required to be able to copy to the clipboard.'
+            exit 1
+        fi
+    else
+        [[ "$(which xsel 2> /dev/null)" != "" ]] && HAS_XSEL=1
+        [[ "$(which xclip 2> /dev/null)" != "" ]] && HAS_XCLIP=1
+
+        if [[ "${HAS_XSEL}${HAS_XCLIP}" = "" ]] ; then
+            echo '"xsel" (preferred) or "xclip" is required to be able to copy to the clipboard.'
+            exit 1
+        fi
     fi
 }
 
 ui_input () {
-    if [ "$IS_DARWIN" != "" ] ; then
+    if [[ "$IS_DARWIN" != "" ]] ; then
         osascript -e "text returned of (display dialog \"$1\" buttons { \"Cancel\", \"OK\" } default button \"OK\" cancel button \"Cancel\" default answer \"\" with icon note)"
-    elif [ "$HAS_ZENITY" != "" ] ; then
+    elif [[ "$HAS_ZENITY" != "" ]] ; then
         zenity --entry --width=320 --text="$1" 2> /dev/null
     else
         kdialog --inputbox "$1" 2> /dev/null
@@ -40,9 +50,9 @@ ui_input () {
 }
 
 ui_error () {
-    if [ "$IS_DARWIN" != "" ] ; then
+    if [[ "$IS_DARWIN" != "" ]] ; then
         osascript -e "display dialog \"$1\" buttons { \"OK\" } default button \"OK\" with icon stop" > /dev/null
-    elif [ "$HAS_ZENITY" != "" ] ; then
+    elif [[ "$HAS_ZENITY" != "" ]] ; then
         zenity --error --width=240 --text="<span size='xx-large'>$1</span>" 2> /dev/null
     else
         kdialog --error "$1" 2> /dev/null
@@ -50,9 +60,9 @@ ui_error () {
 }
 
 ui_info () {
-    if [ "$IS_DARWIN" != "" ] ; then
+    if [[ "$IS_DARWIN" != "" ]] ; then
         osascript -e "display alert \"$1\" message \"$2\" buttons { \"OK\" } default button \"OK\" as informational" > /dev/null
-    elif [ "$HAS_ZENITY" != "" ] ; then
+    elif [[ "$HAS_ZENITY" != "" ]] ; then
         zenity --info --width=400 --text="<span size='xx-large' face='monospace'>$1</span>\n\n$2" 2> /dev/null
     else
         kdialog --msgbox "$1\n$2" 2> /dev/null
@@ -60,9 +70,11 @@ ui_info () {
 }
 
 ui_clipboard () {
-    if [ "$IS_DARWIN" != "" ] ; then
+    if [[ "$IS_DARWIN" != "" ]] ; then
         echo -n "$1" | pbcopy
-    elif [ "$HAS_XSEL" != "" ] ; then
+    elif [[ "$IS_WAYLAND" != "" ]] ; then
+        echo -n "$1" | wl-copy
+    elif [[ "$HAS_XSEL" != "" ]] ; then
         # "xclip" is not working with clipboard sharing in VMware, so "xsel" is preferred
         xsel -d -p
         echo -n | xsel -s
@@ -72,10 +84,14 @@ ui_clipboard () {
     fi
 }
 
-[ "$(uname -s)" = "Darwin" ] && PATH="/usr/local/bin:$PATH" # .profile isn't taken into account when running from Alfred
+[[ "$(uname -s)" = "Darwin" ]] && PATH="/usr/local/bin:$PATH" # .profile isn't taken into account when running from Alfred
 ui_check
 
 PHRASE="$(ui_input "Phrase")"
+
+if [[ "$PHRASE" = "" ]] ; then
+    exit 0
+fi
 
 if ! [[ "$PHRASE" =~ ^[[:space:]]*([^ ]+)([[:space:]]+([0-9uU!@#$%^&*()]+))?[[:space:]]*$ ]] ; then
     ui_error "Unrecognized phrase format"
@@ -86,7 +102,7 @@ TEXT="${BASH_REMATCH[1]}"
 SPEC="${BASH_REMATCH[3]}"
 
 for BNAME in "$HOME/.config/eightsines.hasher"/* ; do
-    [ ! -f "$BNAME" ] && continue
+    [[ ! -f "$BNAME" ]] && continue
 
     BVALUE="$(cat "$BNAME")"
     BNAME="$(basename "$BNAME")"
@@ -105,11 +121,11 @@ HASH="$(echo -n "$TEXT" | sha1sum | sed 's/[ +\-]*$//g')"
 [[ "$SPEC" =~ [uU] ]] && SPEC_UPPERCASE=1
 [[ "$SPEC" =~ ([!@#$%^&*()]) ]] && SPEC_SYMBOL="$BASH_REMATCH"
 
-if [ "$SPEC_LENGTH" != "" ] ; then
+if [[ "$SPEC_LENGTH" != "" ]] ; then
     HASH="${HASH:0:$SPEC_LENGTH}"
 fi
 
-if [ "$SPEC_UPPERCASE" != "" ] ; then
+if [[ "$SPEC_UPPERCASE" != "" ]] ; then
     if [[ "$HASH" =~ [^0-9] ]] ; then
         HASH="$(echo -n "$HASH" | perl -ne 'print $1 . uc($2) . $3 if /^(.*?)([^0-9])(.*)$/')"
     else
@@ -117,11 +133,11 @@ if [ "$SPEC_UPPERCASE" != "" ] ; then
     fi
 fi
 
-if [ "$SPEC_SYMBOL" != "" ] ; then
+if [[ "$SPEC_SYMBOL" != "" ]] ; then
     HASH="${HASH}${SPEC_SYMBOL}"
 fi
 
-if [ "$HASH" = "" ] ; then
+if [[ "$HASH" = "" ]] ; then
     ui_error "Empty result"
     exit 1
 fi
